#!/usr/bin/env ruby

git_bundles = [
  "git://github.com/mattn/gist-vim.git",
  "git://github.com/mattn/webapi-vim",
  "git://github.com/tpope/vim-git.git",
  "git://github.com/vim-ruby/vim-ruby.git",
  "git://github.com/tpope/vim-markdown.git",
  "git://github.com/scrooloose/nerdtree.git",
  "git://github.com/altercation/vim-colors-solarized.git",
  "git://github.com/wincent/Command-T.git",
  "git://github.com/scrooloose/nerdcommenter.git",
  "git://github.com/tpope/vim-fugitive.git",
  "git://github.com/tpope/vim-surround.git",
  "git://github.com/tpope/vim-repeat.git",
  "git://github.com/Lokaltog/vim-powerline.git",
  "git://github.com/kien/ctrlp.vim.git" 
]

require 'fileutils'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")
FileUtils.cd(bundles_dir)

puts "trashing everything (lookout!)"
Dir["*"].each { |dir| FileUtils.rm_rf dir }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end

