#!/bin/bash

# General aliases
alias bitch,="sudo"
alias rm="rm -i"
alias mv="mv -i"
alias cp="cp -i"
alias py="python"
alias rb="ruby"
alias kilall='killall'

# ls
alias ls="ls -F"
alias l='ls -1'
alias ll='ls -l'
alias la='ls -A'
alias lal="ls -Al"
alias d='cd'
alias cl='clear'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../../'

# use vimpager as a pager
export PAGER=vimpager

# Git
alias git='hub'
alias g='git'
alias gs='git status -sb'

# completions
alias ga='git add'
alias gp='git push'
alias gpl='git pull'
alias gd='git diff'
alias gb='git branch -v'
alias gm='git merge'
alias gco='git checkout'

complete -o default -o nospace -F _git g
complete -o default -o nospace -F _git_push gp
complete -o default -o nospace -F _git_pull gpl
complete -o default -o nospace -F _git_diff gd
complete -o default -o nospace -F _git_branch gb
complete -o default -o nospace -F _git_merge gm
complete -o default -o nospace -F _git_checkout gco

## Commiting
alias gc='git commit -v'
alias gca='git commit -av'
alias gcm='git commit -m'
alias gcp='git commit -p'

alias todo="vim ~/Dropbox/tasks/todo.txt"
