#!/bin/bash

# Handy 'tools'
alias sym='ln -s'
alias bp='bitpocket'

# General aliases
alias bitch,="sudo"
alias ll='ls -l'
alias la='ls -A'
alias lr='ls -R'
alias lx='ll -BX'
alias l='ls'
alias lm='la | more'
alias lal="ls -Al"
alias d='cd'
alias cl='clear'
alias pid='pidof'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../../'
alias q=".."
alias grep="grep --color=auto"
alias reload="source ~/.bashrc"
alias py="python2.7"

# use vimpager instead of less
export PAGER=~/.bin/vimpager
alias less=$PAGER

# Git
alias git='hub'
alias g='git'
alias ga='git add'
alias gp='git push'
alias gpl='git pull'
alias gd='git diff'
alias gs='git status -sb'
alias gb='git branch -v'
alias glog='git log --oneline'
alias gm='git merge'
alias gco='git checkout'

## Commiting
alias gc='git commit -v'
alias gca='git commit -av'
alias gcm='git commit -m'
alias gcp='git commit -p'

# Typo correctors
alias kilall='killall'
