#!/bin/bash

# Handy 'tools'
alias sym='ln -s'
alias bp='bitpocket'

# General aliases
alias bitch,="sudo"
alias rm="rm -i"
alias mv="mv -i"
alias py="python"
alias rb="ruby"
alias curdate='date +%d.%m.%y\ %H:%M'

## ls
alias ls="ls -F"
alias l='ls'
alias ll='ls -l'
alias l1='ls -1'
alias la='ls -A'
alias lal="ls -Al"
alias d='cd'
alias cl='clear'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../../'

# use vimpager instead of less
export PAGER=vimpager
alias less=$PAGER

# Git
alias git='hub'
alias g='git'
alias ga='git add'
alias gp='git push'
alias gpl='git pull'
alias gd='git diff'
alias gst='git status -s'
alias gs='gst'
alias gb='git branch -v'
alias gm='git merge'
alias gco='git checkout'

## Commiting
alias gc='git commit -v'
alias gca='git commit -av'
alias gcm='git commit -m'
alias gcp='git commit -p'

# Typo correctors
alias kilall='killall'
