#!/bin/bash

tmux_ssh () {
  tmux new-window -n $1 "/usr/bin/ssh $*"
}

case "$TERM" in
  screen-*)
    alias nssh=/usr/bin/ssh "$@"
    alias ssh="tmux_ssh"
    ;;
esac

alias tcopy='tmux save-buffer -| pbcopy'

