#!/bin/sh

mkdir -p ~/.vim/pack/bundle/start
mkdir -p ~/.psql_history

if [ ! -e "$HOME/.config/kitty/current-theme.conf" ]; then
  cp \
    "$HOME/.config/kitty/themes/whitescale-light.conf" \
    "$HOME/.config/kitty/current-theme.conf"
fi
