#!/bin/sh

mkdir -p ~/.vim/pack/bundle/start
mkdir -p ~/.psql_history

if [ ! -f "$HOME/.config/kitty/theme.conf" ]; then
  ln -fs \
    "$HOME/.config/kitty/light.conf" \
    "$HOME/.config/kitty/theme.conf"
fi
