#!/bin/sh

set -e

command -v rustup >/dev/null 2>&1 || {
  echo >&2 "rustup(1) is not installed."
  exit 78
}

install_toolchain() {
  if ! rustup toolchain list | grep -q "$1"; then
    rustup toolchain install "$@"
  fi
}

set_default_toolchain() {
  if ! rustup show active-toolchain | grep -q "$1"; then
    rustup default "$1"
  fi
}

install_toolchain nightly
set_default_toolchain nightly

rustup component add rust-src
rustup component add rustfmt-preview
rustup component add clippy-preview --toolchain=nightly

command -v racer >/dev/null 2>&1 || {
  cargo install racer
}
