#!/bin/sh

bundles="
  altercation/vim-colors-solarized
  kana/vim-textobj-user
  kchmck/vim-coffee-script
  nelstrom/vim-textobj-rubyblock
  pbrisbin/vim-mkdir
  teoljungberg/vim-focus-on-nearest-test
  teoljungberg/vim-grep-motion
  teoljungberg/vim-visual-star-search
  thoughtbot/pick.vim
  tommcdo/vim-exchange
  tpope/vim-abolish
  tpope/vim-bundler
  tpope/vim-commentary
  tpope/vim-dispatch
  tpope/vim-endwise
  tpope/vim-fugitive
  tpope/vim-git
  tpope/vim-markdown
  tpope/vim-pathogen
  tpope/vim-projectionist
  tpope/vim-rails
  tpope/vim-rake
  tpope/vim-repeat
  tpope/vim-sleuth
  tpope/vim-surround
  tpope/vim-unimpaired
  tpope/vim-vinegar
  vim-ruby/vim-ruby
"

for bundle in ${bundles}; do
  bundle_name=$(echo $bundle | tr "/" "\n" | tail -1)
  vim_bundle=~/.vim/bundle/$bundle_name

  if [ -d $vim_bundle ]; then
    echo "updating $vim_bundle"
    cd $vim_bundle
    git checkout --quiet master
    git fetch --quiet origin
    git --no-pager log --oneline ..origin/master
    git reset --quiet --hard origin/master
  else
    git clone "git://github.com/$bundle" $vim_bundle
  fi
done

if [ -d ~/.vim/vendor ]; then
  for bundle in $(ls ~/.vim/vendor); do
    vim_bundle=~/.vim/vendor/$bundle
    cd $vim_bundle

    if [ $(git remote) ]; then
      echo "updating $vim_bundle"
      git checkout --quiet master
      git fetch --quiet origin
      git --no-pager log --oneline ..origin/master
      git reset --quiet --hard origin/master
    fi
  done
fi
