#!/bin/sh
# No arguments: `git status`
# With arguments: acts like `git`

git() {
  original_git=$(whence -p git)

  if [ $# -gt 0 ]; then
    $original_git "$@"
  else
    $original_git status -sb
  fi
}
