#!/bin/sh

ssh() {
  if [ -z "$TMUX" ]; then
    /usr/bin/ssh "$@"
    return
  fi

  remote="$1"
  old_name="$(tmux display-message -p "#W")"

  if [ -n "$remote" ]; then
    tmux rename-window "$remote"
  fi

  /usr/bin/ssh "$@"

  tmux rename-window "$old_name"
}
