#!/bin/sh

# this speaks for itself
backup_location="/Volumes/Teo500GB/backup/"

# directories to backup. recursive, implied to be in home (~)
directories=(
  Music
  Pictures
  Books
)
RSYNC_OPTS="-aLPhz --partial --delete --log-file=$backup_location/`date +d+m+y`.log"

# if --quiet is passed on as an argument, rsync doesnt show the process of the
# backup
if [ -d $backup_location ]
then
  if [ "$1" == '-q' ]
  then
    is_quiet=true
    ADDITIONAL_OPTS='--quiet'
  elif [ "$1" == '' -o "$1" == '-v' ]
  then
    ADDITIONAL_OPTS='--verbose'
  fi

  # BACKUP COMMENCE
  for directory in ${directories[@]}
  do
    if $is_quiet 
    then
      rsync $RSYNC_OPTS $ADDITIONAL_OPTS ~/$directory $backup_location
    else
      echo 'backing up' $directory
      rsync $RSYNC_OPTS $ADDITIONAL_OPTS ~/$directory $backup_location
      echo 
    fi
  done
else
  echo "$backup_location is not present"
fi

