#!/bin/sh
#
# Quick shortcut to Finder
#
# USAGE:
#
# $ f
# # => opens the current directory in Finder
#
# $ f .
# $ f /usr/local
# # => opens the specified directory in Finder

if [ "$1" = "" ]; then
  open -a Finder "."
else
  open -a Finder "$1"
fi
