#!/usr/bin/env ruby

require 'colored'

def header(header)
  puts "--> ".blue + "#{header}"
end

def cmd(cmd)
  puts "    $ #{cmd}".green
  system cmd
end

header "Updating Vim plugins"
cmd "cd ~/.homesick/repos/dotfiles && git submodule --quiet foreach git pull origin master"

header "Updating Homebrew"
cmd "brew update --rebase"

header "Upgrading Homebrew"
cmd "brew upgrade -v"

header "Let Homebrew clean up"
cmd "brew cleanup -v"

header "Removing Homebrew cache"
cmd "rm -rf ~/Library/Caches/Homebrew/*"

header "Remove screenshots from desktop"
cmd "rm -rfv ~/Desktop/*Screen\ Shot*.png"

header "Taking out the trash"
cmd "rm -rf ~/.Trash/*"

