#!/usr/bin/env ruby

require 'colored'

def header(header)
  puts "---> ".blue + "#{header}"
end

def cmd(cmd)
  puts "\t$ #{cmd}".green
  system cmd
end

header "Updating Vim plugins"
cmd "cd ~/.homesick/repos/dotfiles && git submodule --quiet foreach git pull origin master"

header "Updating Homebrew"
cmd "brew update --rebase && brew upgrade -v && brew cleanup -v"

header "Removing Homebrew cache"
cmd "rm -rf ~/Library/Caches/Homebrew/*"

header "Remove screenshots from desktop"
cmd "rm -rfv ~/Desktop/*Screen\ Shot*.png"

header "Taking out the trash"
cmd "rm -Rf ~/.Trash/*"

