#!/bin/bash

echo "Updating Vim plugins.."
cd ~/Dropbox/dotfiles
git submodule foreach git pull origin master
cd ~

echo "Updating, Updating and Pruning Homebrew.."
brew update && brew upgrade -v && brew cleanup -v

echo "Updating Homebrew repository"
cd ~/git/homebrew/
git pull upstream master
cd ~

echo "Removing Homebrew cache.."
rm -rfv ~/Library/Caches/Homebrew/*

echo 'Updating Gist'
~/.bin/latest-gist

echo 'Updating Ack'
~/.bin/latest-ack

echo 'Updating Hub'
~/.bin/latest-hub

echo "Taking out the trash.."
rm -rf ~/.Trash/*

echo "Backing up"
backup 
