#!/bin/bash
#
# Usage: 
#    reminder "Leave to catch the bus" 14:20
#    reminder "Take soda out of the freezer" "now + 60 minutes"
#    reminder "Check if Friend #2 paid me" "4pm tomorrow"
#
# (see `man at` for more time commands)

at $2 << !!
osascript -e 'tell app "System Events" to display dialog "$1"'
!!

exit 0
