#!/bin/bash

# ls
alias ls="ls -F --color=always"

# ls colors
eval `dircolors ~/.dircolors`

# Applications
alias db='dropbox'
alias weechat='weechat-curses'
alias bp='bitpocket'
alias aur='pbget --aur-only'
