#!/bin/bash

# EDITOR
export EDITOR=mvim

# 'Applications'
alias te='open -a TextEdit'
alias vlc='open -a VLC'
alias brewup='brew update --rebase && brew upgrade -v && brew cleanup -v'

# Clipboard
alias pbp="pbpaste"
alias pbc="pbcopy"

# Typos
alias brweup='brewup'
alias brwe='brew'
