#!/bin/bash

# EDITOR
export EDITOR=mvim

# 'Applications'
alias te='open -a TextEdit'
alias firefox='open -a Firefox'
alias vlc='open -a VLC'
alias brewup='brew update && brew upgrade -v && brew cleanup -v'

# Clipboard
alias pbp="pbpaste"
alias pbc="pbcopy"

# Typos
alias brwe="brew"
alias brweup='brewup'
