#!/bin/bash

# ls
alias ls='gls -F --color=always'

# ls colors
eval `gdircolors ~/.dircolors/dir_colors-dark` 

# Applications
alias te='open -a TextEdit'
alias vlc='open -a VLC'
alias brewup='brew update && brew upgrade -v && brew cleanup -v'

# Clipboard
alias pbp="pbpaste"
alias pbc="pbcopy"

# Typos
alias brweup='brewup'
alias brwe="brew"
