#!/bin/sh

set -e
[ -n "$DEBUG" ] && set -ex

git_dir="$(git rev-parse --git-dir)"
tmpfile=$(mktemp /tmp/ctags.XXXXXX)

if [ -d "$git_dir/safe" ]; then
  trap 'rm -f "$tmpfile"' EXIT INT TERM

  if [ -f Gemfile ] && which ripper-tags 1>/dev/null 2>/dev/null; then
    git ls-files --cached --exclude-standard --others | \
      ripper-tags -L - -f "$tmpfile"
  else
    git ls-files --cached --exclude-standard --others | \
      ctags -L - -f "$tmpfile"
  fi

  mv "$tmpfile" tags
fi
