#!/bin/sh

set -e

PATH="/usr/local/bin:$PATH"
dir="$(git rev-parse --git-dir)"

trap 'rm -f "$dir/$$.tags"' EXIT

if [ -f Gemfile ] && ripper-tags -h 1> /dev/null 2> /dev/null; then
  if [ -n "$SKIP_RIPPER" ]; then
    git ls-files --cached --exclude-standard --others | \
      ctags --append --tag-relative -L - -f "$dir/$$.tags"
  else
    git ls-files --cached --exclude-standard --others | \
      ripper-tags --append --tag-relative -L - -f "$dir/$$.tags"

    git ls-files --cached --exclude-standard --others | \
      ctags --append --languages=-ruby, --tag-relative -L - -f "$dir/$$.tags"
  fi
else
  git ls-files --cached --exclude-standard --others | \
    ctags --tag-relative -L - -f "$dir/$$.tags"
fi

mv "$dir/$$.tags" "$dir/tags"
