#!/bin/sh

set -e
[ -n "$DEBUG" ] && set -ex

dir="$(git rev-parse --git-dir)"

if [ -d "$dir/safe" ]; then
  trap 'rm -f "$dir/$$.tags"' EXIT

  if [ -f Gemfile ] && which ripper-tags 1>/dev/null 2>/dev/null; then
    ctags_command="ripper-tags"
  else
    ctags_command="ctags"
  fi

  git ls-files --cached --exclude-standard --others |
    "$ctags_command" --tag-relative -L - -f "$dir/$$.tags"

  mv "$dir/$$.tags" "$dir/tags"
fi
